language: php

php:
  - 7.2
  - 7.3
  - 7.4
  - 8.0

env:
  - SYMFONY_VERSION=~4.1.0

matrix:
  include:
    - php: 7.2
      env: SYMFONY_VERSION=~3.1.0
    - php: 7.2
      env: SYMFONY_VERSION=~3.0.0
    - php: 7.2
      env: SYMFONY_VERSION=~2.4
    - php: 7.2
      env: SYMFONY_VERSION=~4.2.0
    - php: 7.3
      env: SYMFONY_VERSION=~4.2.0
    - php: 7.4
      env: SYMFONY_VERSION=~4.2.0
    - php: 7.2
      env: SYMFONY_VERSION=~5.0.0
    - php: 7.3
      env: SYMFONY_VERSION=~5.0.0
    - php: 7.4
      env: SYMFONY_VERSION=~5.0.0
    - php: 8.0
      env: SYMFONY_VERSION=~5.0.0
    - php: 7.4
      env: SYMFONY_VERSION=~6.0.0
    - php: 8.0
      env: SYMFONY_VERSION=~6.0.0

before_script:
  - composer require "symfony/framework-bundle:${SYMFONY_VERSION}" --no-update
  - composer install --no-interaction --dev
