language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1

env:
  - SYMFONY_VERSION=~3.1.0

matrix:
  include:
    - php: 5.5
      env: SYMFONY_VERSION=~3.0.0
    - php: 5.6
      env: SYMFONY_VERSION=~3.0.0
    - php: 7.0
      env: SYMFONY_VERSION=~3.0.0
    - php: 7.1
      env: SYMFONY_VERSION=~3.0.0
    - php: 5.5
      env: SYMFONY_VERSION=~2.4
    - php: 5.6
      env: SYMFONY_VERSION=~2.4
    - php: 7.0
      env: SYMFONY_VERSION=~2.4
    - php: 7.1
      env: SYMFONY_VERSION=~2.4

before_script:
  - composer require "symfony/framework-bundle:${SYMFONY_VERSION}" --no-update
  - composer install --no-interaction --dev
